name: After server responds
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  cypress-run:
    strategy:
      matrix:
        dotnet: [ 6.0.x ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    name: E2E on ${{ matrix.os }} using .NET ${{ matrix.dotnet }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: dotnet run --project ReactProj
          # quote the url to be safe against YML parsing surprises
          wait-on: 'https://localhost:44459'
