name: After server responds
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  cypress-run:
    strategy:
      matrix:
        dotnet: [ 6.0.x ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    name: E2E on ${{ matrix.os }} using .NET ${{ matrix.dotnet }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: .NET run
        run: dotnet run --project ReactProj &
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: http://localhost:5216
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "false"
          # String representation of cookie attached to health check request.
          # Format: `Name=Value`
          # cookie: "token=asdf1234" # Optional, default is empty
          # Basic auth login password pair.
          # Format: `login:password`
          # basic-auth: "login:password" # Optional, default is empty
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # quote the url to be safe against YML parsing surprises
          wait-on: 'https://localhost:44459'
